apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  sustainable-computing.io/app: kepler
resources:
- serviceaccount.yaml
- service.yaml
- daemonset.yaml
- servicemonitor.yaml
