apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    sustainable-computing.io/app: kepler
  name: kepler-leader-election
  namespace: kepler-monitoring
rules:
  - apiGroups:
      - ''
    resources:
      - nodes/metrics
      - nodes/proxy
      - nodes/stats
    verbs:
      - get
      - list
      - watch
