apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kepler
  namespace: argocd
spec:
  project: cluster-management
  source:
    path: kepler/overlays/emea/morty
    repoURL: https://github.com/operate-first/apps.git
    targetRevision: HEAD
  destination:
    name: morty
    namespace: kepler-monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Validate=false